/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/Tools/Anlogic/Projects/IT8951/al_ip/stack_ram.v
 ** Date	:	2020 07 11
 ** TD version	:	4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module stack_ram ( doa, dia, addra, cea, clka, wea );

	output [3:0] doa;

	input  [3:0] dia;
	input  [9:0] addra;
	input  wea;
	input  cea;
	input  clka;



	EG_LOGIC_BRAM #( .DATA_WIDTH_A(4),
				.ADDR_WIDTH_A(10),
				.DATA_DEPTH_A(1024),
				.DATA_WIDTH_B(4),
				.ADDR_WIDTH_B(10),
				.DATA_DEPTH_B(1024),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K(FAST)"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({4{1'b0}}),
				.addra(addra),
				.addrb({10{1'b0}}),
				.cea(cea),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(wea),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule